export const AUTHENTICATE = "AUTHENTICATE";
export const UNAUTHENTICATE = "UNAUTHENTICATE";
export const IMAGEUPDATE = "IMAGEUPDATE";
export const UPDATEFULLNAMEANDBIO = "UPDATEFULLNAMEANDBIO";
export const UPDATESOCIALMEDIA = "UPDATESOCIALMEDIA";
export const PULLINFO = "PULLINFO";
export const LOGOUT = "LOGOUT";
export const PULLINFOVIEW = "PULLINFOVIEW";
